structures:
  bastionremnant: true
  buriedtreasure: false
  desertpyramid: true
  endcity: true
  fortress: true
  igloo: true
  junglepyramid: true
  mansion: true
  mineshaft: false
  monument: true
  netherfossil: true
  oceanruin: false
  pillageroutpost: true
  ruinedportal: true
  shipwreck: false
  stronghold: true
  swamphut: true
  village: true
layer:
  name: "Structures"
  hidebydefault: false
  layerprio: 10
  nolabels: false
  minzoom: 0
  inc-coord: false
